// Generated by CoffeeScript 1.3.1
(function() {

  window.append = function() {
    return $("#tests").append("test case1");
  };

  window.ajax = function() {
    return $.ajax({
      url: 'sample.json'
    }).done(function(items) {
      var item, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        _results.push($("#tests").append(JSON.stringify(item)));
      }
      return _results;
    });
  };

  window.destroy = function(name, father) {
    eric.name = name;
    return eric.family.father.name = father;
  };

  window.append_test = {
    name: "append test",
    func: "append"
  };

  window.ajax_test = {
    name: "ajax test",
    func: "ajax",
    is_ajax: true
  };

  window.destroy_test = {
    name: "destroy test",
    func: "destroy",
    arg: ["destroyer", "darth vader"],
    json_paths: ['window.eric']
  };

  window.eric = {
    name: "eric",
    company: "google",
    intro: function() {
      return console.log(this.name);
    },
    family: {
      father: {
        name: 'mark',
        comapny: 'facebook',
        intro: function() {
          return console.log(this.name);
        }
      },
      mother: {
        name: 'mary',
        company: 'horizon'
      }
    }
  };

}).call(this);
